platform :ios, '15.0'

target 'CardManagementSDKSwiftSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #old API
  #pod 'NICardManagementSDK', '~> 1.0'
  
  #new API
  pod 'NICardManagementSDK'#, '1.2.2'
  
  #dev mode
  #pod 'NICardManagementSDK', :path => '~/Documents/projects/card-management-sdk-ios'

end
